name: jordanguanga
favicon: null
layout_spectrum: 0.22016
typography_spectrum: 0.11625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#718eac'
    - '#2d4a58'
    - '#e3cb8b'
    - '#001300'
    - '#628508'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
