name: jordanguanga
favicon: null
layout_spectrum: 0.46344123641029
typography_spectrum: 0.6883368312846869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.873202602379024
  lightness: 0.16570783988572657
  saturation: 0.9916873627807945
  rhythmicContrast: 0.08720124652609229
purpose: []
